In [4]:
#numpy makes it easy to do computations on large datasets. 
#for matrices, multiplication and division with arrays is done column wise.

import numpy as np
from numpy.random import randn

In [9]:
np.set_printoptions(precision=2)

In [10]:
# Creating arrays using a list - 
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [13]:
array_2 = np.array([[10,20,30],[40,50,60]])
array_2

array([[10, 20, 30],
       [40, 50, 60]])

In [16]:
array_3 = np.random.randn(6)
array_3

array([ 2.62, -0.2 , -0.17, -0.5 ,  1.03, -1.65])

In [20]:
array_4 = np.arange(1,35)
print(array_4)
for val in array_4:
    print(val)
#NumPy Arrays are iterable

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34


In [21]:
array*10

array([10, 20, 30, 40, 50, 60])

In [23]:
array_2/[1,2,3]

array([[10, 10, 10],
       [40, 25, 20]])

In [24]:
array_3 + array

array([ 3.62,  1.8 ,  2.83,  3.5 ,  6.03,  4.35])

In [26]:
array-array_3

array([-1.62,  2.2 ,  3.17,  4.5 ,  3.97,  7.65])

In [27]:
array_3*array

array([ 2.62, -0.39, -0.52, -2.02,  5.15, -9.89])

In [28]:
array_3/array

array([ 2.62, -0.1 , -0.06, -0.13,  0.21, -0.27])

In [29]:
aa = np.array([[2.,4.,6.],[1.,3.,5.],[10.,20.,30.]])
aa

array([[  2.,   4.,   6.],
       [  1.,   3.,   5.],
       [ 10.,  20.,  30.]])

In [30]:
bb = np.array([[0.,1.,2.],[1.,3.,5.],[10.,20.,30.]])
bb

array([[  0.,   1.,   2.],
       [  1.,   3.,   5.],
       [ 10.,  20.,  30.]])

In [31]:
aa*bb #this is NOT matrix multiplication. values are just multiplied based on indices. 

array([[   0.,    4.,   12.],
       [   1.,    9.,   25.],
       [ 100.,  400.,  900.]])

In [33]:
aa-bb

array([[ 2.,  3.,  4.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [34]:
aa+bb

array([[  2.,   5.,   8.],
       [  2.,   6.,  10.],
       [ 20.,  40.,  60.]])

In [35]:
aa.dot(bb) #this is matrix multiplication but this will be dot product for arrays

array([[   64.,   134.,   204.],
       [   53.,   110.,   167.],
       [  320.,   670.,  1020.]])

In [36]:
array.dot(array_3) #dot product

-5.0402000061193917